### ISSUE TITLE
Pull components we rely on from `openff-models` into `gufe`

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/gufe#397]
It is unlikely that [`openff-models`](https://github.com/openforcefield/openff-models) will have future releases, and none of the OpenFF stack currently depends on it (recently, the small bits `openff-interchange` were depending on where merged directly in to that library).

Because of this, it makes sense for us to identify the pieces of `openff-models` `gufe` currently depends on and migrate those pieces directly into `gufe`. We can follow this up with simplification where possible.

**Comment by IAlibay** [comment]
This needs more discussion - it's unclear to me that we want to take the openff-models code instead of the refactor that is now in interchange.

**Comment by dotsdl** [comment]
@IAlibay I'll examine interchange for what it has against `openff-models`, and make a decision on what to pull.

**Comment by IAlibay** [comment]
@dotsdl just as an FYI - openff-models is now archived, with things having fully switched over to interchange in the openff ecosystem.

**Comment by dotsdl** [comment]
Thanks @IAlibay! I'll start with using the `openff-interchange` implementation. Will identify any changes needed downstream to accommodate this.

**Comment by dotsdl** [comment]
@mikemhenry and @IAlibay: looking in detail at this, we use `openff-models` in only one place: [`gufe.settings.models`](https://github.com/OpenFreeEnergy/gufe/blob/bda5e74b4d6a096036e37dcb9adc3ff82c006076/gufe/settings/models.py#L11-L12).

Do you recall what functionality we specifically wanted to take advantage of from `openff-models` for the purposes of our `Settings` models? I'm trying to determine what we actually need here vs. just surgically removing what we use from `openff-models` and vendoring it into the `gufe` codebase.

**Comment by dotsdl** [comment]
In `openff-interchange`, into which the components of `openmm-models` it needed were migrated and refactored, `FloatQuantity` no longer exists as a concept, and `DefaultModel` (now `_BaseModel`) no longer implements a custom quantity encoder.

@mattwthompson can you comment as to why you were able to dispense with much of the machinery from `openff-models` when incorporating them into `openff-interchange`? Are the workarounds `openff-models` did just no longer necessary?

**Comment by dotsdl** [comment]
A related question to the above for @mattwthompson: is the refactored implementation in `openff-interchange` possible due to `pydantic` 2?

**Comment by mattwthompson** [comment]
The functionality you need it at least JSON serialization/deserialization of `Quantity`s since Pydantic doesn't know how to do it out of the box. For example:

```python
from openff.units import Quantity
from pydantic import BaseModel, ConfigDict


class Status(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    temperature: Quantity
    pressure: Quantity


print(
    Status.model_validate_json(
        Status(
            temperature=Quantity("313 kelvin"),
            pressure=Quantity("0.99 bar"),
        ).model_dump_json()
    )
)
"""
Traceback (most recent call last):
  File "/Users/mattthompson/software/openff-interchange/397.py", line 17, in <module>
    ).model_dump_json()
      ^^^^^^^^^^^^^^^^^
  File "/Users/mattthompson/micromamba/envs/openff-interchange-env/lib/python3.12/site-packages/pydantic/main.py", line 477, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pint.Quantity'>
"""
```

There's also some built-in magic that can i.e.
* Cast inputs to float, so the user can give 298 (as an integer) and it's later processed as 298.0
* Cast inputs to `Quantity` with a given unit, so i.e. 273.15 is converted internally to the same thing as `Quantity(273.15, "kelvin")`

The code that comprised `openff-models` was really just two files and it ended up being simpler to just move them into Interchange than think about how to slowly migrate all of the dependency trees[^1]. The hacks that we used ~4 years ago don't map neatly onto V2 so a heavier refactor was necessary. For example, the serialization which previously appeared to live on the `DefaultModel` now "lives" in the annotation which is tagged to each Pydantic field. (I think [this](https://github.com/openforcefield/openff-interchange/blob/v0.4.2/openff/interchange/_annotations.py#L110), for example, is how stuff like `_TemperatureQuantity` knows how to serialize to JSON, including dealing with arrays, and that connection is made based on how much stuff is [shoved into the `Annotation` definition](https://github.com/openforcefield/openff-interchange/blob/v0.4.2/openff/interchange/_annotations.py#L169)). The workaround are still necessary, although it's possible there are better ways to get everything (NumPy, Pint, Pydantic, JSON, and a little bit of OpenMM) to play nicely together than the solution I settled into last fall.

IIRC all of that code is V2-only; rephrased, all released `openff-models` code is V1 only and anything V2 is after I vacuumed it up into Interchange directly.

I'm not sure if your best path forward here is a partial re-implementation of what's already in this files[^2] or vendoring them directly[^3]. I'm pretty sure just the two files `openff/interchange/pydantic.py` and `openff/interchange/_annotations.py` can act like a self-contained little thing, copy-pasted as a starting point. It should all be vendor-friendly MIT code and I'm happy to see it yoinked out if that's what easiest for you here

[^1]: Around this time, I was maybe overly eager to split every little thing into its own microrepo
[^2]: A good chunk of the hassle is dealing with arrays, like positions from either the toolkit or OpenMM, so if you're only dealing with scalar quantities, things get a little simpler. Like ["only 1 LOC to do each important step"](https://github.com/openforcefield/openff-interchange/blob/v0.4.2/openff/interchange/_annotations.py#L121-L124) sort of simple!
[^3]: Having `openff-interchange-base` as a dependency for this package is probably not worth the weight

**Comment by dotsdl** [comment]
Thank you so much for this @mattwthompson! This context is incredibly helpful!

I'm considering the options you laid out; will proceed with a PR once I think I have something that meets the needs in `gufe`.

**Comment by IAlibay** [comment]
@dotsdl thanks for the ping, I don't have a lot of capacity to think this through right now but let's discuss this at a gufe meeting.

**Comment by dotsdl** [comment]
All good @IAlibay! I think @mattwthompson gave me plenty of context on the existing behavior we want to retain for me to proceed!

**Comment by dotsdl** [comment]
From `gufe` working session with @atravitz, @jthorton, @ianmkenney, we decided on the following:
1. we will vendor `openff-models` components that we currently rely on for our `Settings` objects into `gufe`, effectively keeping these on `pydantic` v1.
2. In the `gufe` 2.0 release cycle, we will evaluate whether `openff-interchange` is stable enough for us to adopt its replacement of this apparatus for our `Settings` objects, effectively moving us to `pydantic` v2 for these objects.
    - if it is stable enough, we will adopt `openff-interchange` as a dependency for `gufe`.
    - if we think it isn't stable enough, we will consider vendoring its components into `gufe` to replace those from `openff-models`.

**Comment by IAlibay** [comment]
> stable enough, we will adopt openff-interchange as a dependency for gufe.

Could we possibly discuss this further? Interchange is a large dependency, I'm not sure it really makes sense to pull it in fully. Why not just vendor what we need?

**Comment by mikemhenry** [comment]
If we only need `openff-interchange-base` I don't think it adds any deps:

```
  - name: openff-interchange-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - versioningit
      run:
        - python >={{ python_min }},<3.14.0a0
        - pydantic =2
        - openff-toolkit-base ~=0.16.6
        - openff-units >=0.2.0,<0.4.0
        - openff-utilities >=0.1.5
```

The non-base version pulls in openmm 8 and the full version of `openff-toolkit`

```
        - python >={{ python_min }},<3.13.0a0
        - openmm =8
        - {{ pin_subpackage('openff-interchange-base', exact=True) }}
        - openff-toolkit ~=0.16.4
        - panedr
```
Which we also pull in (actually we don't pull in `openff-toolkit` just `openff-toolkit-base`).

**Comment by IAlibay** [comment]
This kinda makes us move away from our dreams of a PyPi releasable gufe :/

**Comment by mikemhenry** [comment]
> dreams of a PyPi releasable gufe

Why are we dreaming of that? I don't object to it but if we want to have that, then we can!

**Comment by IAlibay** [comment]
> I don't object to it but if we want to have that, then we can!
This is mostly that the OpenFF stack will probably never go on PyPi.

Another thought:
From a discussion with @dotsdl today - we need to consider that we might eventually pull in pablo for PDB reading, so maybe we're all bought in on the OpenFF stack.
